# Generated by Django 4.2.29 on 2026-03-29 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reportapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=reportapp.models.generate_reference, editable=False, max_length=20, unique=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('water', 'Water & Sanitation'), ('electricity', 'Electricity & Load Shedding'), ('roads', 'Roads & Potholes'), ('waste', 'Waste & Refuse Collection'), ('housing', 'Housing & Property'), ('parks', 'Parks & Recreation'), ('safety', 'Public Safety & Lighting'), ('other', 'Other')], default='other', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location_address', models.CharField(max_length=300)),
                ('ward_number', models.CharField(blank=True, max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('notify_whatsapp', models.BooleanField(default=False)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='reportapp.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('updated_by', models.CharField(default='System', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='reportapp.complaint')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
